INSERT INTO areas (name) VALUES
('Main Hall'),
('East Wing'),
('West Wing'),
('North Wing'),
('South Wing'),
('Entrance Hall'),
('Exit Hall'),
('Room 1'),
('Room 2'),
('Room 3'),
('Room 4'),
('Room 5'),
('Room 6'),
('Room 7'),
('Room 8'),
('Room 9'),
('Room 10');

INSERT INTO institutions (name, information) VALUES
('Museum of Modern Art', '11 W 53rd St, New York, NY 10019, USA'),
('The Louvre', 'Rue de Rivoli, 75001 Paris, France'),
('The British Museum', 'Great Russell St, Bloomsbury, London WC1B 3DG, UK'),
('The Metropolitan Museum of Art', '1000 5th Ave, New York, NY 10028, USA'),
('The State Hermitage Museum', 'Palace Square, 2, Sankt-Peterburg, Russia, 190000'),
('The Vatican Museums', 'Viale Vaticano, 00165 Roma RM, Italy'),
('The National Gallery', 'Trafalgar Square, Charing Cross, London WC2N 5DN, UK'),
('The Museum of Fine Arts', '465 Huntington Ave, Boston, MA 02115, USA'),
('The Rijksmuseum', 'Museumstraat 1, 1071 XX Amsterdam, Netherlands'),
('The Uffizi Gallery', 'Piazzale degli Uffizi, 6, 50122 Firenze FI, Italy'),
('The Prado Museum', 'Calle de Ruiz de Alarcón, 23, 28014 Madrid, Spain'),
('The National Museum of Korea', '137 Seobinggo-ro, Seobinggo-dong, Yongsan-gu, Seoul, South Korea'),
('The National Museum of China', '16 E Chang''an Ave, Dongcheng, Beijing, China, 100006'),
('The National Museum of Anthropology', 'Av. Paseo de la Reforma s/n, Polanco, Bosque de Chapultepec I Secc, 11560 Ciudad de México, CDMX, Mexico'),
('The National Museum of Natural History', '10th St. & Constitution Ave. NW, Washington, DC 20560, USA'),
('The National Museum of American History', '1300 Constitution Ave NW, Washington, DC 20560, USA'),
('The National Museum of African American History and Culture', '1400 Constitution Ave NW, Washington, DC 20560, USA'),
('The National Museum of the American Indian', '4th St SW & Independence Ave SW, Washington, DC 20560, USA'),
('Robert Jones', 'email: bob@bob.bob, phone: 1234567890'),
('Alice Smith', 'email: alice.smith.1441@bob.bob, phone: 0987654321');

-- generates 100 artifacts. Don't repeat items. Thry have to be unique. Status is 'available' because other statuses would require associations with other tables
INSERT INTO artifacts (name, description, category, status, ownership, inspection_duration) VALUES
('Star of India', 'A large, blue star sapphire weighing 563.35 carats (112.67 g), the largest such gem in the world.', 'Gemstone', 'available', 'owned', '1 day'),
('The Hope Diamond', 'A large, 45.52-carat, deep-blue diamond, now housed in the National Gem and Mineral collection at the National Museum of Natural History in Washington, D.C.', 'Gemstone', 'available', 'owned', '1 day'),
('The Cullinan Diamond', 'The largest gem-quality rough diamond ever found, weighing 3,106.75 carats (621.35 g), discovered in 1905.', 'Gemstone', 'available', 'owned', '1 day'),
('The Koh-i-Noor Diamond', 'A large, colourless diamond that was found in the Kollur Mine, India, probably in the 13th century.', 'Gemstone', 'available', 'owned', '1 day'),
('The Regent Diamond', 'A 141 carats (28.2 g) diamond that is now in the Louvre, Paris.', 'Gemstone', 'available', 'owned', '1 day'),
('The Orlov Diamond', 'A large, 189.62-carat diamond that is part of the collection of the Diamond Fund of the Moscow Kremlin.', 'Gemstone', 'available', 'owned', '1 day'),
('The Sancy Diamond', 'A pale yellow diamond of 55.23 carats (11.05 g) that once belonged to the Mughal emperors.', 'Gemstone', 'available', 'owned', '1 day'),
('The Blue Moon Diamond', 'A 12.03-carat blue diamond, now known as the Blue Moon of Josephine, was discovered in South Africa in January 2014.', 'Gemstone', 'available', 'owned', '1 day'),
('The Wittelsbach-Graff Diamond', 'A 31.06-carat (6.212 g) deep-blue diamond that has been artificially coloured.', 'Gemstone', 'available', 'owned', '1 day'),
('The Dresden Green Diamond', 'A 41 carats (8.2 g) natural green diamond, which probably originated in the Kollur mine in the state of Andhra Pradesh in India.', 'Gemstone', 'available', 'owned', '7 days'),
('The Mona Lisa', 'A half-length portrait painting by the Italian artist Leonardo da Vinci, which has been described as "the best known, the most visited, the most written about, the most sung about, the most parodied work of art in the world".', 'Painting', 'available', 'owned', '7 days'),
('The Last Supper', 'A late 15th-century mural painting by Leonardo da Vinci housed by the refectory of the Convent of Santa Maria delle Grazie in Milan.', 'Painting', 'available', 'owned', '7 days'),
('The Creation of Adam', 'A fresco painting by Michelangelo, which forms part of the Sistine Chapel''s ceiling.', 'Painting', 'available', 'owned', '7 days'),
('Guernica', 'A mural-sized painting by Pablo Picasso that depicts the suffering of people and animals wrenched by violence and chaos.', 'Painting', 'available', 'owned', '7 days'),
('The Persistence of Memory', 'A 1931 painting by artist Salvador Dalí, and is one of his most recognizable works.', 'Painting', 'available', 'owned', '7 days'),
('The Starry Night', 'A painting by the Dutch post-impressionist artist Vincent van Gogh.', 'Painting', 'available', 'owned', '7 days'),
('The Night Watch', 'A 1642 painting by Rembrandt van Rijn, which is housed in the Rijksmuseum in Amsterdam.', 'Painting', 'available', 'owned', '7 days'),
('The Birth of Venus', 'A painting by the Italian artist Sandro Botticelli, probably made in the mid 1480s.', 'Painting', 'available', 'owned', '7 days'),
('The Scream', 'A painting by the Norwegian artist Edvard Munch, which shows a figure with an agonized expression against a landscape with a tumultuous orange sky.', 'Painting', 'available', 'owned', '7 days'),
('Girl with a Pearl Earring', 'A painting by the Dutch Golden Age painter Johannes Vermeer.', 'Painting', 'available', 'owned', '7 days'),
('The Thinker', 'A bronze sculpture by Auguste Rodin, usually placed on a stone pedestal.', 'Sculpture', 'available', 'owned', '7 days'),
('David', 'A masterpiece of Renaissance sculpture created in marble between 1501 and 1504 by the Italian artist Michelangelo.', 'Sculpture', 'available', 'owned', '7 days'),
('The Venus de Milo', 'An ancient Greek statue and one of the most famous works of ancient Greek sculpture.', 'Sculpture', 'available', 'owned', '7 days'),
('The Winged Victory of Samothrace', 'A marble Hellenistic sculpture of Nike (the Greek goddess of victory), that is believed to have been created about 190 BC.', 'Sculpture', 'available', 'owned', '7 days'),
('The Pieta', 'A work of Renaissance sculpture by Michelangelo Buonarroti, housed in St. Peter''s Basilica, Vatican City.', 'Sculpture', 'available', 'owned', '7 days'),
('The Discobolus', 'A famous lost Greek bronze original, which was completed towards the end of the Severe period, circa 460–450 BC.', 'Sculpture', 'available', 'owned', '7 days'),
('The Terracotta Army', 'A collection of terracotta sculptures depicting the armies of Qin Shi Huang, the first Emperor of China.', 'Sculpture', 'available', 'owned', '7 days'),
('The Great Sphinx of Giza', 'A limestone statue of a reclining sphinx, a mythical creature with the body of a lion and the head of a human.', 'Sculpture', 'available', 'owned', '7 days'),
('The Statue of Liberty', 'A colossal neoclassical sculpture on Liberty Island in New York Harbor in New York City.', 'Sculpture', 'available', 'owned', '7 days'),
('The Kiss', 'A marble sculpture by the French sculptor Auguste Rodin.', 'Sculpture', 'available', 'owned', '7 days'),
('The Gates of Hell', 'A monumental sculptural group work by French artist Auguste Rodin that depicts a scene from "The Inferno", the first section of Dante Alighieri''s Divine Comedy.', 'Sculpture', 'available', 'owned', '7 days'),
('The Burghers of Calais', 'A sculpture by Auguste Rodin that commemorates an occurrence during the Hundred Years'' War.', 'Sculpture', 'available', 'owned', '7 days'),
('Blopy opy glopy', 'A sculpture by Auguste Rodin that commemorates an occurrence during the Hundred Years'' War.', 'Sculpture', 'available', 'owned', '7 days'),
('Random painting with unique name', 'Just to fill up the space', 'Painting', 'available', 'owned', '2 months'),
('Some sculpture or whatever', 'It was sculpted or not, I dont care anymore', 'Sculpture', 'available', 'owned', '5 hours');


